// tests/architecture/gate-2g1 — THE FINAL 2G.1 GATE MANIFEST.
//
// ─── WHAT THIS IS, AND WHAT IT REFUSES TO BE ───────────────────────────────────────────────────
//
// 2G.1 closes by INTEGRATING evidence, not by adding behaviour. This file is the declared inventory
// of every suite in the repository and what each one is worth as evidence for that closure.
//
// It exists because of a mistake made during slice 5: a suite whose `beforeAll` THREW was read as
// "skipped", because vitest prints a failed suite's tests the same way it prints a genuinely gated
// one — and the misreading survived two sessions and reached the contract, the ledger and memory.
//
//   > A filtered test run is not a test result. "Skipped" and "the suite threw in beforeAll" print
//   > the same count.
//
// So the classification is DECLARED here and CHECKED by `gate-2g1.test.ts`, which fails closed: a
// suite claimed PROVEN whose environment gate is unset fails the gate rather than passing quietly.
//
// ─── THE FIVE CLASSES, AND WHY THE DISTINCTION IS THE POINT ────────────────────────────────────
//
//   PROVEN          an executed, controlled proof — it ran, in this run, with a discriminating
//                   control that can go red
//   OBSERVED        production behaviour is consistent with the property, WITHOUT a control in the
//                   loop. Never promoted to PROVEN because the system looks healthy
//   BLOCKED         infrastructure prevented execution. Recorded, never silently counted as a pass
//   PARKED          a known finding or act deliberately deferred to a later layer
//   NOT_APPLICABLE  the property does not belong to this layer
//
// A healthy production server produces OBSERVED facts. It never produces PROVEN ones.

export type Evidence = "PROVEN" | "OBSERVED" | "BLOCKED" | "PARKED" | "NOT_APPLICABLE";

/**
 * WHEN a proof runs. Two independently MEASURED constraints forced this (§26.6, §26.7):
 *
 *   A · the server phase writes probe routes into `app/`, which static scans (F41, F51, F54) see
 *       if they run concurrently — measured as three architecture failures
 *   B · the server phase's Turbopack compilation burst starves real network round-trips, which
 *       time out at Vitest's 5s default — measured, and cleared of any database cause
 *
 * These are HARNESS CONSTRAINTS, not implementation defects. Nothing collides; the phases simply
 * cannot share a machine.
 *
 *   > The manifest says what a proof requires; the scripts enforce when that proof runs.
 */
export type Phase = "static" | "server" | "db";

export type GateEntry = {
  readonly evidence: Evidence;
  /** Which phase must run this suite. Checked against the file's directory AND its behaviour. */
  readonly phase: Phase;
  /** Why this classification. Required for every entry — an unexplained class is not evidence. */
  readonly why: string;
  /**
   * Environment variables the suite needs in order to RUN.
   *
   * Load-bearing rather than documentation: the gate asserts that every PROVEN entry's variables are
   * present in the run making the claim. Presence only — never values (see the credential incident).
   */
  readonly requires?: readonly string[];
};

/**
 * EVERY test file in the repository. Totality, in the shape F49 uses for routes and F51 for pages:
 * a suite with no entry is an ERROR, not an implicit pass, and an entry naming no file means the
 * manifest is describing a repository that moved on.
 */
export const GATE_2G1: Record<string, GateEntry> = {
  "tests/api/invitations-mint.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.3 \u00a728.4/\u00a728.13 \u2014 the minting route: unauthenticated 401, sales 403, owner 201, malformed id 400; a non-member is refused BY THE ATOMIC INSERT \u2026 SELECT predicate \u2014 the statement executes and inserts zero rows" },
  "tests/api/route-matrix.test.ts": { evidence: "PROVEN", phase: "static", why: "2F 7.4 — all 27 routes, both roles, double denial" },
  "tests/api/search-boundary.test.ts": { evidence: "PROVEN", phase: "static", why: "scoped at assembly, with the unscoped mutation control" },
  "tests/api/threat-model.test.ts": { evidence: "PROVEN", phase: "static", why: "STAGE2F §11 threat model, demonstrated through real handlers" },
  "tests/architecture/f51-page-demand.test.ts": { evidence: "PROVEN", phase: "static", why: "F51 — declared == observed capability demand, 31/31" },
  "tests/architecture/f56-nav-contract.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.3 F56 — every nav destination is a classified page and `requires` equals the page contract exactly" },
  "tests/architecture/fitness.test.ts": { evidence: "PROVEN", phase: "static", why: "F1-F50, F52, F54/F55, F58 — machine-enforced rules incl. the invite-separation invariant" },
  "tests/intake/projection.test.ts": { evidence: "PROVEN", phase: "static", why: "Stage 2 Sheets 2C \u2014 \u00a71.4's three blank-cell states as a pure mapping: a present-but-blank website never becomes website_quality none, closed vocabularies are validated rather than guessed, an unrecognised boolean is UNSTATED not false, and no projection can carry a judgment field" },
  "tests/intake/batch.test.ts": { evidence: "PROVEN", phase: "static", why: "Stage 2 Sheets 2A \u2014 the intake foundation: verbatim parsing proven AGAINST lib/csv's trimming as the discriminating witness, \u00a71.4's absent-column vs empty-cell distinction, and \u00a71.2's rule that re-importing the same bytes is a new batch with the same file_sha256" },
  "tests/intake/delimiter-agreement.test.ts": { evidence: "PROVEN", phase: "static", why: "the 2026-09-04 TSV import regression — a tab-separated sheet is read as tab-separated rather than as one column, detection is taken from the header line so a comma inside a data cell cannot outvote it, and the two BYTE-IDENTICAL copies of detectDelimiter (lib/csv and core/intake/batch, duplicated because core imports nothing from lib) are fed the same ten sheets and asserted to split them into the same columns — the discriminating witness being that the copies could silently diverge and attach values to the wrong column in the evidence or the projection" },
  "tests/intake/column-inference.test.ts": { evidence: "PROVEN", phase: "static", why: "header → field mapping as a pure function: one header binds at most one field and one field at most one header, exact spellings are resolved for EVERY field before any loose pattern runs anywhere (the ordering bug that bound Contact Email to the contact's NAME), bare 'name' is the business rather than the contact, and — the case that produced 3,193 garbage prospects — a sheet with no recognisable business-name column maps NO name instead of defaulting to headers[0]" },
  "tests/auth/event-visibility.test.ts": { evidence: "PROVEN", phase: "static", why: "the event spine's per-domain visibility model \u2014 a SYNTHETIC principal narrowed by a hoisted mock of can() (the capability table is never edited) proves a prospects:read-only caller sees the prospect event and NOT the invoice or document ones, that the result is a PROPER subset and non-empty, that the caller's requested domains/types grant nothing, that an unidentified caller obtains nothing, and that an unmapped prefix (notifications, deferred) stays visible" },
  "tests/auth/authority-classification.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.4.5 \u00a729.3 Ruling 3 \u2014 every PageDenial reaches requireCapability as the contracted class, both directions per row, with compiler-enforced totality over the union" },
  "tests/auth/dal-boundary.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.1 slice 2a/2b — all eight storage boundaries refuse an unauthorized caller" },
  "tests/auth/dal-mutation-gate.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.1 slice 2c — a module-level principal leaks observably under barrier-proven overlap" },
  "tests/auth/index-scoping.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.1 slice 4 — C1/C2 closed at the filesystem: sales opens zero client/SOP files" },
  "tests/auth/landing.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.3 \u00a728.6/\u00a728.12 \u2014 the landing DECISION and the login JOURNEY: a sales credential signs in and is routed to /partner" },
  "tests/auth/nav-visibility.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.3 \u00a728.7/\u00a728.12 \u2014 the rail a partner actually sees, with authority established explicitly and a non-empty control" },
  "tests/auth/nav-boundary.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.3 F57 — every destination hidden from sales refuses sales on a DIRECT render, with a visible-destination control" },
  "tests/auth/page-denial.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.1 slice 3 — denial classified server-side by type; notFound/redirect survive" },
  "tests/auth/page-principal.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.1 slice 1 — the React.cache page resolver and its 22 refusal directions" },
  "tests/auth/portal-token-boundary.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.1 slice 2d — a client token reaches only its own client" },
  "tests/auth/request-context.test.ts": { evidence: "PROVEN", phase: "static", why: "7.2 the request-context trust boundary, and the prospect seam's unit proof with its control" },
  "tests/auth/session-v2.test.ts": { evidence: "PROVEN", phase: "static", why: "the session token carries no role and cannot be edited into authority" },
  "tests/cognition/cooccurrence.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/cognition/plasticity.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/cognition/propagation.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/cognition/utility-harness.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  // These suites carry a file-scoped DOM environment; the project default stays `node`. They
  // mount the real client components and drive them — §28.12's "presence is not behaviour".
  "tests/recovery/artifact.test.ts": { evidence: "PROVEN", phase: "static", why: "R1a \u2014 the encrypted artifact: AES-256-GCM round trip; a flipped bit in header, body or tag refuses to open and releases no plaintext; wrong and missing keys refused by id; the key never appears in any encoding inside an artifact and a key that leaked into the inputs is refused; key files must be 0600 and outside the repository, the backup directory and iCloud; rotation opens old artifacts by their own key id; an interrupted write leaves no artifact under the final name" },
  "tests/ui/invite-panel.test.ts": { evidence: "PROVEN", phase: "static", why: "2G.3 \u00a728.4/\u00a728.12 \u2014 the owner mints THROUGH THE UI: selection, request shape, link, clipboard, refusals" },
  "tests/ui/touch-floor.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "1C \u2014 the interaction floor as a STYLESHEET CONTRACT: its pointer/width condition, its confinement to the operator and public columns, its exclusion of the Galaxy, and the checkbox exclusion from the 44px field rule. It claims no geometry \u2014 happy-dom has no stylesheet, viewport or pointer; the measured 44px/16px/focus-clearance facts are the rendered CDP pass. Not a 2G.1 authorization property" },
  "tests/ui/wipe-panel.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "1C \u2014 the first mount of WipePanel, proving the D1 layout hooks changed nothing it DOES: default selection, toggling, the exact-WIPE gate, the POST body, refusal and transport-failure handling. Behaviour only, never placement. The route authorizes independently and is covered by the wipe API suites" },
  "tests/ui/shell-overlays.test.ts": { evidence: "PROVEN", phase: "static", why: "1A \u2014 the shell's two modal surfaces DRIVEN rather than read: a desktop-collapsed preference still yields a labelled phone drawer, focus lands on the close control and returns to the trigger, a chosen destination sends focus to content instead, Escape is stopped before it reaches the Galaxy behind, and the drawer's capture-phase claim on \u2318K is proven by the RETURN path \u2014 the mutation that removes it leaves the palette opening normally and stranding focus only on the way out. It proves BEHAVIOUR, not PLACEMENT: happy-dom applies no stylesheet and has no viewport, so the drawer's geometry, the palette's keyboard clearance and the timer's phone region are acceptance-criterion-7 rendered checks and are NOT claimed here" },
  "tests/db/consumer-parity.test.ts": { evidence: "PROVEN", phase: "db", why: "substrate/consumer behaviour exercised in-process against PGlite" },
  "tests/db/intake-route.test.ts": { evidence: "PROVEN", phase: "db", why: "Stage 2 Sheets 2F \u2014 the REAL /api/import/prospects handler, invoked the way Next invokes it with a real signed cookie against the full 001-007 migration set and ASCEND_PROSPECT_SOURCE=postgres: the guard still refuses an unauthenticated caller, one POST produces both the projection and its correlated verbatim evidence, a dry run mutates NOTHING (no prospect AND no event), and \u00a72.1's identity resolution reaches the route" },
  "tests/db/intake-second-import.test.ts": { evidence: "PROVEN", phase: "db", why: "Stage 2 Sheets 2E \u2014 all seven \u00a77.3(d) cases against a real Postgres, each asserting the NEGATIVE the contract forbids: unchanged is not suppressed, changed does not rewrite batch 1 (compared whole as JSON), ABSENT IS NOT DELETED and not even marked, duplicate and conflict keep their evidence with prospect_id null, and a re-import leaves an existing judgment and its author intact with a non-vacuity control proving the batch did record something" },
  "tests/db/intake-identity.test.ts": { evidence: "PROVEN", phase: "db", why: "Stage 2 Sheets 2D \u2014 \u00a72.1's five outcomes with discriminating witnesses: BLOCKED proven to be evaluated FIRST by a row corroborating a held record AND an anchored one, so only the ORDER decides (P4's collapse); name-alone rejected with a name+locality control; a duplicate within one sheet resolves to matched; evidence survives every refusal with prospect_id null" },
  "tests/db/intake-projection.test.ts": { evidence: "PROVEN", phase: "db", why: "Stage 2 Sheets 2C \u2014 ASCEND FOUND through the EXISTING writer: prospect.created firing is the discriminating witness that core/db.createProspect was used rather than a bespoke INSERT; unprojected rows keep their evidence with prospect_id null; re-import leaves the first batch byte-identical; judgment columns asserted NULL with a non-vacuity control" },
  "tests/db/d1-promotion.test.ts": { evidence: "PROVEN", phase: "db", why: "D1a \u2014 prospect mutations against the store that owns them, through the REAL promote/DELETE handlers and the real admission chain (cookie \u2192 membership-resolved principal) on PGlite + a throwaway vault: the row is marked and `prospect.promoted` lands on the POSTGRES spine with the caller's actor_user_id; the hit list is byte-identical (M1); a retry with any client slug reuses one client (M2); the status change and its event are one transaction (M5); a mid-promotion failure reports INCOMPLETE and the retry converges (M4); a partial client write leaves nothing visible (M6/M6b); ambiguous and held references are refused with nothing written (M7/M8); Postgres-mode deletion refuses without touching the mirror (M9); every vault prospect writer refuses in postgres mode (M11); an unreadable vault file is never overwritten (M12). Ten mutation probes each turn it red" },
  "tests/db/note-idempotency.test.ts": { evidence: "PROVEN", phase: "db", why: "2A.0-C \u2014 note writes are idempotent through the REAL POST /api/prospects/[slug]/notes handler and the real admission chain on PGlite 001\u2013009. The note id is client-generated, REQUIRED and validated; a sequential retry, a lost-response retry, five retries, a trimmed retry and an upper-case retry each converge on ONE row and ONE prospect.note_added event (correlation_id = note id) and return the SAME note (201 then 200 replayed). Different ids are different notes. The same id with a different body, prospect or author is refused 409 and reveals nothing of the other note; nothing is appended. Unauthenticated 401, a missing prospect 404, and authorship stays the resolved principal whatever the request names. Five mutation probes (no ON CONFLICT, server-minted ids, an event on replay, replay without the sameness check, an optional id) each turn it red" },
  "tests/db/note-idempotency-concurrency.test.ts": { evidence: "PROVEN", phase: "db", why: "2A.0-C \u2014 note idempotency under REAL concurrency on PostgreSQL 17.6 (the retained verified build; Unix socket only; one backend per request, proven distinct). Eight simultaneous writes of ONE id make ONE row and ONE event with one 201 and seven replays; eight different ids make eight notes; two bodies racing under one id store exactly one and refuse the other. Deterministically: a retry arriving while the original is UNCOMMITTED waits on the uniqueness lock and then replays it; if the original ROLLS BACK, the waiting retry writes the note. PGlite has one backend and cannot overlap two writes, so this entry FAILS the environment gate on purpose until ASCEND_PG17_BIN names a PostgreSQL >= 17 build", requires: ["ASCEND_PG17_BIN"] },
  "tests/db/d1-archival.test.ts": { evidence: "PROVEN", phase: "db", why: "D1b \u2014 prospect ARCHIVAL through the REAL DELETE handler and the real admission chain (cookie \u2192 membership-resolved principal; no forged principal anywhere, F59) on PGlite carrying 001\u2013009 plus a throwaway vault. Owner and sales each archive and are attributed to THEMSELVES; a repeat is an idempotent 200 already_archived with the first archiver and instant kept and exactly ONE prospect.archived event; a held prospect is refused 409 held for BOTH roles with nothing written; not_found is 404 and an ambiguous slug is 409 with a count. Notes, the markdown body, the identity anchor and the whole prior event trail all survive (a hard DELETE would cascade the notes away, 008). The archived row leaves the active reader and STAYS in the explicit one, in findCorroborating, in findByProspectId and in getProspect \u2014 including the import matcher\u2019s universe, with an archived fixture proving a re-import is not classified `new`. Promotion of an archived prospect is refused with NO client created. Least privilege proven against the database: sales holds no DELETE, exactly two archive columns and nothing wider, automation holds nothing, an archived row is unwritable by sales while the owner retains FOR ALL, cross-org is invisible, and archival_has_provenance refuses a half-stated archival in both directions. The vault arm still deletes and emits prospect.deleted" },
  "tests/db/d1-concurrency.test.ts": { evidence: "PROVEN", phase: "db", why: "D1b \u2014 the concurrency debt D1a carried, closed against a REAL PostgreSQL 17.6 server (production\u2019s version, built from verified official source into a private disposable root; Unix socket only, no TCP listener) with a real connection pool, so each in-flight request is its own backend. PGlite CANNOT stand in: it has one backend, so it can neither observe a race nor survive a blocking advisory lock \u2014 which is why this entry FAILS the environment gate on purpose until ASCEND_PG17_BIN names a PostgreSQL >= 17 build. Eight simultaneous archives make ONE transition and ONE event with the first archiver kept; two \u2014 and then six \u2014 simultaneous promotions each asking for a DIFFERENT client slug produce exactly ONE client directory and ONE prospect.promoted, with every caller converging on that same client (the D1a hole: its compare-and-set guarded the status and the event, never the filesystem client write between two transactions); promotion racing archival is repeated six times and holds for BOTH orderings \u2014 never both archived and newly won, never a promoted claim from the loser, never more than one client, notes intact. A note appended DURING an archival lands attached and readable with no deadlock", requires: ["ASCEND_PG17_BIN"] },  "tests/db/graph-projection-scoping.test.ts": { evidence: "PROVEN", phase: "db", why: "GraphProjection Slice 1 \u2014 Part Zero \u00a70.5's scoping witness, built rather than observed because the two production roles' authorized universes are IDENTICAL today: a synthetic narrowed principal proves the projection FAILS CLOSED with no partial graph, and two organizations with genuinely different authorized data prove the narrower projection is a PROPER subset, with a both-non-empty control so neither is small for the wrong reason" },
  "tests/research/candidates.test.ts": { evidence: "PROVEN", phase: "static", why: "website-candidate derivation as a pure function, tested for CONSERVATISM rather than recall: a free-provider address (gmail/yahoo/sbcglobal/pacbell — 1,702 of the imported leads) yields NO candidate because it is evidence about the mail host and not the business, a record already stating a website yields none at all, a name too short or purely punctuation yields none, and the company email domain outranks the name guess so a business is never attributed a domain merely guessed from its name" },
  "tests/db/research-website.test.ts": { evidence: "PROVEN", phase: "db", why: "the research runner against a real Postgres, whose SUBJECT is the negative outcome: when nothing answers, `website_quality` stays NULL — the assertion that matters, since `none` is worth +30 in computeScore, exactly the warm threshold, and a failed probe is indistinguishable from slow DNS or a blocked crawler. Also proven: a 404 from a live server is still not-found, a run that finds nothing records that Ascend LOOKED (actor `system`, with candidates and per-probe failures as evidence) while writing no prospect field, an existing website is never overwritten, and — at the database rather than by reading the runner — `ascend_automation` is refused UPDATE on `website_opportunity` while succeeding on `website`, the control proving the refusal is the grant and not a broken connection" },
  "tests/db/prospect-notes.test.ts": { evidence: "PROVEN", phase: "db", why: "008's note log against a real Postgres, asserting what the migration claims is IMPOSSIBLE with a discriminating control for each: `ascend_automation` cannot append AND cannot read the operator's voice (controlled by a sales principal succeeding in the same test), NO role may UPDATE a note (controlled by the owner's DELETE succeeding), sales cannot sign a note as a colleague — the `author_user_id = current_user_id()` policy — a blank note is refused however spelled, another organization reads nothing through RLS, notes cascade with the prospect they annotate, and `prospect.note_added` is an OPERATOR event carrying the note id but NOT its prose, so an owner's delete leaves no copy in the append-only spine" },
  "tests/db/intake-evidence.test.ts": { evidence: "PROVEN", phase: "db", why: "Stage 2 Sheets 2B \u2014 THE SHEET SAID as append-only events against a real Postgres: verbatim cells survive jsonb, a second import adds evidence and leaves the first byte-identical, correlation_id partitions the batches, append-only asserted at the GRANT catalog rather than by the absence of an update path, and ordering proven with event_ids CONSTRUCTED to contradict append order" },
  "tests/db/invitations.test.ts": { evidence: "PROVEN", phase: "db", why: "F53 (2G.2) \u2014 invitation tokens hashed, single-use and atomic; least privilege proven by GRANT" },
  // 2G.2 operational gates. ONE-SHOT and production-mutating, so they classify the way 2D/2D.1/2E's
  // migration gates do: their evidence is the waypoint that recorded them (a6f4068), not a re-run.
  "tests/db/production-2g4-007.test.ts": { evidence: "PARKED", phase: "db", why: "the 007 production gate \u00a728.14 item 7 called REQUIRED and UNBUILT \u2014 applies the FILTERED 007 to production over the direct endpoint, then proves what the server enforces: the composite FK with ON DELETE RESTRICT, the recreated INSERT policy with both conjuncts, and three rolled-back behavioural witnesses gathered AS ascend_owner rather than as the superuser the migration excludes", requires: ["ASCEND_MIGRATE_007_URL"] },
  "tests/db/production-2g4-credential-read.test.ts": { evidence: "PARKED", phase: "db", why: "2G.4.6 \u00a729.3 Ruling 5 \u2014 row 11's production half, split out of production-2f-partner as a read-only rollback-scoped probe against the POOLER, with an ascend_auth control. Built and NEVER EXECUTED: withheld pending \u00a729.11 Q2, which is a decision and not an obstacle", requires: ["ASCEND_CREDENTIAL_PROBE_URL"] },
  "tests/db/production-2g2-invitations.test.ts": { evidence: "NOT_APPLICABLE", phase: "db", why: "one-shot; applied 006 to production; its read-only verification half is re-runnable on demand" },
  "tests/db/production-2g2-provision.test.ts": { evidence: "NOT_APPLICABLE", phase: "db", why: "one-shot; re-provisioned ascend_app; SET ROLE proof re-runnable on demand" },
  // EXECUTED 2026-08-30 under explicit authorization. Classified like every other one-shot
  // production gate: its evidence is the WAYPOINT that recorded it, not a re-run. PROVEN would be
  // wrong here and the gate would say so — PROVEN means "ran in THIS run", and this suite skips
  // without its two variables.
  "tests/db/production-2g2-acceptance.test.ts": { evidence: "NOT_APPLICABLE", phase: "db", why: "one-shot; rollback-scoped acceptance EXECUTED against production and passed 2026-08-30 \u2014 \u00a727.17; evidence is the waypoint 07e7f45", requires: ["ASCEND_ACCEPT_TEST_URL", "ASCEND_ACCEPT_VERIFY_URL"] },
  "tests/db/savepoint-client.test.ts": { evidence: "PROVEN", phase: "db", why: "the savepoint adapter the acceptance gate rests on, incl. a control that it can never COMMIT" },
  "tests/db/mutation.test.ts": { evidence: "PROVEN", phase: "db", why: "substrate/consumer behaviour exercised in-process against PGlite" },
  "tests/db/page-matrix-provisioned.test.ts": { evidence: "PROVEN", phase: "db", why: "2G.4.3 §8 row 2, row 6 page-side and row 7 — 29 pages × both roles through the REAL admission chain (cookie, Next's own work/work-unit request scope, verifySessionToken, resolvePrincipal), including the admin disclosure recorded as measured fact and a revocation by a real disabled_at write, distinguished by reason from a database outage; own PGlite and vault fixture, no external endpoint; does not exercise the App Router, middleware, or React.cache memoization" },
  "tests/db/pooled-principal.test.ts": { evidence: "PROVEN", phase: "db", why: "2D — a pooled connection carries no principal between checkouts", requires: ["ASCEND_TEST_DATABASE_URL"] },
  "tests/db/production-2e-consumer-parity.test.ts": { evidence: "PROVEN", phase: "db", why: "2E consumer parity against real production, executed once IPv6 egress returned", requires: ["ASCEND_DATABASE_URL", "ASCEND_DATABASE_URL_DIRECT"] },
  "tests/db/production-2e-migration.test.ts": { evidence: "NOT_APPLICABLE", phase: "db", why: "2E one-shot; migrated the six prospects; evidence is 2E's waypoint", requires: ["ASCEND_MIGRATE_PROSPECTS_URL"] },
  "tests/db/production-2e-raw-parity.test.ts": { evidence: "PROVEN", phase: "db", why: "2E raw parity \u2014 vault bytes against production columns, executed once IPv6 egress returned", requires: ["ASCEND_DATABASE_URL_DIRECT"] },
  "tests/db/production-2e-source-flip.test.ts": { evidence: "PROVEN", phase: "db", why: "2E source-of-truth flip against real production, executed once IPv6 egress returned", requires: ["ASCEND_DATABASE_URL", "ASCEND_DATABASE_URL_DIRECT"] },
  "tests/db/production-2f-partner.test.ts": { evidence: "PARKED", phase: "db", why: "provisions the partner — that is 2G.2's act, deliberately not run while users = 1", requires: ["ASCEND_PROVISION_PARTNER_URL"] },
  "tests/db/production-app-login.test.ts": { evidence: "PROVEN", phase: "db", why: "the application login holds no ambient authority \u2014 executed against the DIRECT endpoint once IPv6 egress returned", requires: ["ASCEND_DATABASE_URL", "ASCEND_DATABASE_URL_DIRECT"] },
  "tests/db/production-authorization.test.ts": { evidence: "PROVEN", phase: "db", why: "RLS and column grants enforce the boundary in the database itself", requires: ["ASCEND_TEST_DATABASE_URL"] },
  "tests/db/production-hardening.test.ts": { evidence: "NOT_APPLICABLE", phase: "db", why: "2D.1 one-shot; writes to production; evidence is 2D.1's waypoint", requires: ["ASCEND_HARDEN_DATABASE_URL"] },
  "tests/db/production-migration.test.ts": { evidence: "NOT_APPLICABLE", phase: "db", why: "2D one-shot; writes schema to production; its evidence is 2D's waypoint", requires: ["ASCEND_MIGRATE_DATABASE_URL"] },
  "tests/db/route-matrix-provisioned.test.ts": { evidence: "PROVEN", phase: "db", why: "2G.4.2 §8 row 1 and row 6 route-side — every route \u00d7 both roles through the REAL admission chain (cookie, verifySessionToken, requireAppDb, resolvePrincipal, can), and revocation by a real disabled_at write; own PGlite and vault fixture, no external endpoint" },
  "tests/db/provisioned-partner.test.ts": { evidence: "PROVEN", phase: "db", why: "2G.4.1 §29.3 Ruling 1 — a partner reaches a resolved principal through the real chain (insert, invite, accept, login, resolve), against its own PGlite and session secret, depending on no external endpoint" },
  "tests/db/request-isolation.test.ts": { evidence: "PROVEN", phase: "db", why: "7.3 THE CRITICAL GATE — barrier-proven overlap, mutant leaks 10 crossings incl. cross-tenant rows", requires: ["ASCEND_DATABASE_URL", "ASCEND_TEST_DATABASE_URL"] },
  "tests/db/restore-fidelity.test.ts": { evidence: "PROVEN", phase: "db", why: "R1a \u2014 the canonical recovery mechanism re-proven on the CURRENT schema (001\u2013008) with rows in all eight tables: manifest \u2192 pg_dump --inserts \u2192 AES-256-GCM seal/open \u2192 restore into a fresh in-process PGlite \u2192 F1\u2013F17 key-for-key, sequence/append-only/RLS/column-grant behaviour, and the application's own readers (login, principal, prospects, notes, events). Notes and invitations are proven HERE because production holds none. Discriminating controls: renumbered seq, lost policy, altered credential, altered note, and the 2D runbook's DROP SCHEMA restore are each caught. Replaces the retired managed-server backup-restore suite. Must run with no connection configuration in the process (npm run recovery:verify); it fails closed otherwise" },
  "tests/db/restore-independence.test.ts": { evidence: "PROVEN", phase: "db", why: "R1 \u2014 the CURRENT production recovery point, restored off-vendor into in-process PGlite and verified F1\u2013F18 against the manifest production produced at dump time, plus the owner\u2019s real login through the application. Its evidence exists only once R1b takes that artifact: until then this entry FAILS the environment gate on purpose \u2014 stale 2D evidence (schema 004, zero rows) is not carried forward, relabelled or grandfathered", requires: ["ASCEND_BACKUP_ARTIFACT", "ASCEND_BACKUP_KEYRING", "ASCEND_RECOVERY_OWNER_EMAIL", "ASCEND_RECOVERY_OWNER_PASSWORD"] },
  "tests/db/restore-same-version.test.ts": { evidence: "PROVEN", phase: "db", why: "R1c \u2014 the SAME production artifact restored onto a real PostgreSQL 17.6 server (official source, built into a private disposable root; no TCP listener, Unix socket only, every connection proving version, data directory and system identifier) over BOTH paths \u2014 the portable-SQL restoreInto and the runbook's pg_restore -L with exactly four TOC entries skipped \u2014 each F1\u2013F18 key-for-key against production's manifest with no F5 normalization needed, plus behaviour; then the application consumes it read-only as the restored ascend_app login through the real pg driver (credentialFor/verifyPassword, resolvePrincipal, listProspects, readEvents, listProspectNotes, invitations under RLS, listOrganizationMembers) on a trigger-guarded clone where every write path is refused and no tuple changes. Needs the build root, which R1c destroys after the proof: until a root is rebuilt this entry FAILS the environment gate on purpose. HTTP (next start) boot is NOT COVERED", requires: ["ASCEND_BACKUP_ARTIFACT", "ASCEND_BACKUP_KEYRING", "ASCEND_RECOVERY_OWNER_EMAIL", "ASCEND_RECOVERY_OWNER_PASSWORD", "ASCEND_R1C_ROOT"] },
  "tests/db/scale.test.ts": { evidence: "PROVEN", phase: "db", why: "substrate/consumer behaviour exercised in-process against PGlite" },
  "tests/db/substrate-migration.test.ts": { evidence: "PROVEN", phase: "db", why: "substrate/consumer behaviour exercised in-process against PGlite" },
  "tests/db/substrate.test.ts": { evidence: "PROVEN", phase: "db", why: "substrate/consumer behaviour exercised in-process against PGlite" },
  "tests/engines/approvals-engine.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/authority-repair.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/command-runtime.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/confirm-gate.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/decision-engine.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/document-engine.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/effort-engine.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/event-emission.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/health-engine.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/identity-backfill.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/intelligence-forecast.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/intelligence-insight.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/migration.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/notification-engine.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/notification-loop.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/onboarding.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/opportunity-engine.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/pipeline-engine.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/prospect-hardening.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/reconciler.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/site-quality-engine.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/engines/sop-engine.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/ui/galaxy-surfaces.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "mounts the two presentation surfaces over one already-authorized Scene and checks they show the same objects. It resolves no caller and holds no policy — what it proves is that the accessible list is not a SECOND data path, which is an architecture property, not an authorization one. F65 holds the boundary and is classified separately" },
  "tests/graph/galaxy-traversal.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "the relationship-traversal authority — a pure function of SceneEdges the projection already asserted and the scene already drew. It resolves no caller and reaches no reader; the relationships it walks were authorized upstream and classified once in graph-view/spatial" },
  "tests/graph/galaxy-celestial.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "the celestial presentation model — a pure function of an ALREADY-AUTHORIZED SceneModel. It resolves no caller and reads no business field; celestial role is a spatial reading of the containment hierarchy, never a domain or authorization concept. F65/F66 hold the boundary and are classified separately" },
  "tests/graph/galaxy-activity.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "the recent-event activation derivation — a pure function of the ALREADY-AUTHORIZED activity the projection carries, the drawn node set, and one clock reading. It resolves no caller; the guarantee that an unauthorized event never reaches that activity list belongs to core/events readEvents and is proven in tests/auth/event-visibility.test.ts" },
  "tests/graph/galaxy-scene.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "the renderer draw model — a pure transformation of an ALREADY-AUTHORIZED projection, spatial model and layout. It receives no principal and resolves none; its LOD filter narrows what is DRAWN, never what was permitted. The rule that keeps it that way is F65 in fitness.test.ts, which is classified separately" },
  "tests/graph/galaxy.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "GalaxyLayout is a pure transformation of an ALREADY-AUTHORIZED SpatialModel — it receives no principal and resolves none, so it carries no 2G.1 authorization property. The rule that keeps it that way is F64 in fitness.test.ts, which is classified separately" },
  "tests/graph/spatial.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "SpatialModel is a pure transformation of an ALREADY-AUTHORIZED projection — it receives no principal and resolves none, so it carries no 2G.1 authorization property. The rule that keeps it that way is F63 in fitness.test.ts, which is classified separately" },
  "tests/graph/viewport.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/graph/galaxy-blackhole.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "the galactic core's geometry and optics — six nested radii, a Keplerian shear law, Doppler beaming and a lensing profile, all pure functions of numbers. It reaches no reader, resolves no caller and carries no business fact; the core represents the agency itself and holds no record of it" },
  "tests/graph/galaxy-spiral.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "the rebuilt Galaxy's star field — a seeded density-wave construction over a count and a string key. It never sees the projection, holds no id and cannot carry a business fact; F66's backdrop conditions hold that by construction and are classified separately" },
  "tests/graph/galaxy-blackbody.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "stellar colour from temperature, and interstellar reddening — a pure function of two numbers. It resolves no caller and reads no business field" },
  "tests/graph/galaxy-field.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "the rebuilt Galaxy's scale table and framing arithmetic — pure geometry over constants. It touches no projection, resolves no caller and reads no business field; the numbers describe a world, not a permission" },
  "tests/ui/galaxy-focus.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "the rebuilt Galaxy's drill-path state machine — which level the camera rests at and which breadcrumb is open. It is presentation state over ids the surface was already handed; it fetches nothing and can widen nothing, so refusing a click mid-transition is a UI lock and never an authorization one" },
  "tests/graph/galaxy-systems.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "buildSystemMap \u2014 role, hierarchy, orbit track and focus bounds derived from an ALREADY-AUTHORIZED projection and spatial model. It receives no principal and resolves none. The business-meaning property it does hold is the opposite of a permission: a satellite shown beside a single project is PLACEMENT and never inferred ownership, and a record whose owner is ambiguous stays in the directory rather than being attached to the nearest star. Routes and permalinks come from navigation/routing and the graph contract, so no id format or destination is rebuilt here" },
  "tests/ui/galaxy-system-ui.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "mounts the directory and inspector over one already-authorized SystemMap and drives client \u2192 project \u2192 invoice, search and the placement note. Every destination it asserts arrived finished on the record; the surface holds no routing table and no policy, so what it proves is that the inspector states the canonical route rather than inventing one \u2014 a presentation property, not an authorization one" },
  "tests/ui/galaxy-stage-failure.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "1B \u2014 failure containment on the renderer that actually ships. It mounts GalaxyStage, GalaxyControls and SurfaceBoundary over one ALREADY-AUTHORIZED SystemMap and proves which surfaces survive which failure: no WebGL mounts no renderer, the directory and its canonical links outlive the picture, a boundary reports once and never remounts what threw, and a post-pass failure costs the effect alone. The set of records it can show is the set it was handed \u2014 a directory that survives a graphics failure resolves no principal, reads no business field and widens nothing, so containment is a presentation property and never an authorization one. Geometry, the white paint of a lost context and real driver failure are NOT claimed here: happy-dom applies no stylesheet and has no WebGL, so those are rendered CDP evidence in docs/PHASE-1B-CHECKPOINT.md" },
  "tests/relationships/derive.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "domain/engine behaviour — not a 2G.1 authorization property" },
  "tests/render/page-isolation.test.ts": { evidence: "PROVEN", phase: "server", why: "2G.1 slice 1 — React.cache isolation under barrier-proven overlap, with a leaking mutant", requires: ["ASCEND_RENDER_TEST"] },
  "tests/render/startup-binding.test.ts": { evidence: "PROVEN", phase: "server", why: "2G.1 slice 5 — real startup binds the resolver both entry points consume; BOUND: same process only", requires: ["ASCEND_STARTUP_TEST", "ASCEND_DATABASE_URL", "ASCEND_TEST_DATABASE_URL"] },  "tests/architecture/gate-2g1.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "this gate itself — it integrates evidence and proves no property of its own" },
  "tests/architecture/gate-2g4.test.ts": { evidence: "NOT_APPLICABLE", phase: "static", why: "the 2G.4 gate itself \u2014 it integrates evidence and proves no property of its own; asserts the accounting is total and internally honest, never that anything behaves" },
};

/**
 * Properties whose only evidence is a healthy production system.
 *
 * Kept SEPARATE from the suite manifest on purpose: these have no controlled proof, and listing them
 * beside proven properties is how an observation gets promoted by proximity.
 */
export const OBSERVED_ONLY: readonly { readonly property: string; readonly why: string }[] = [
  {
    property: "the deployed build serves every prospect-reading page",
    why: "after rebuilding to 654fe56, /finance /sales /sales/<slug> /console / /crm /signals all " +
         "answer 200 with zero errors, and /finance had returned 500 before. Consistent with the " +
         "prospect bridge working in production — but no control was in the loop, so it is not proof",
  },
  {
    property: "startup binds the database at boot",
    why: "the service logs '[startup] application database bound (TLS-verified, pooled, no ambient " +
         "identity)'. Consistent with correct wiring, and equally consistent with a resolver bound " +
         "by something else — which is exactly why slice 5 built a controlled proof instead",
  },
  {
    property: "a nonexistent prospect slug returns 404 in production, not a denial or a 500",
    why: "slice 3's unstable_rethrow observed in a real build. Proven in-process; here only observed",
  },
];

/** Findings deliberately carried out of 2G.1. The gate asserts they are NOT silently fixed here. */
export const PARKED_FINDINGS: readonly { readonly finding: string; readonly owner: string }[] = [
  { finding: "admin, admin/import, admin/wipe and dashboard declare [] so a sales principal renders them (no data leaks — those routes are guarded)", owner: "2G.4" },
  { finding: "a membership revoked mid-session reaches the error boundary rather than a named surface", owner: "2G.4" },
  { finding: "discoverClients/discoverSops read the vault directly rather than through the guarded readers — an asymmetry, not an escape path", owner: "2G.4" },
  { finding: "invitation tokens hashed and single-use (F53, reserved)", owner: "2G.2" },
  { finding: "partner UI", owner: "2G.3" },
  { finding: "Sheets intake", owner: "after 2G.4" },
];
