// The frozen STRUCTURAL corpus, snapshotted from the live vault on 2026-08-19 alongside
// REAL_STREAM in ./fixtures.
//
// It is a snapshot for the same reason the activation stream is: the retrospective utility
// experiment (docs/COGNITION-OBSERVATION.md §15) must be reproducible forever, and a live-vault
// read would change the moment another client is onboarded. An experiment whose inputs move cannot
// be re-run, and a pre-registered experiment that cannot be re-run is not one.
//
// 98 foreign-key relationships. The 8 `flags` edges the projection also draws are absent by
// construction — relationships/ refuses engine judgments at its boundary (F23.7).

import type { StructuralRelationship, StructuralRelationshipKind } from "@/relationships/contract";
import type { EntityKind } from "@/domain";

const r = (
  se: EntityKind,
  si: string,
  te: EntityKind,
  ti: string,
  kind: StructuralRelationshipKind
): StructuralRelationship => ({
  source: { entity: se, entity_id: si },
  target: { entity: te, entity_id: ti },
  kind,
  provenance: { reader: "snapshot", field: "snapshot" },
});

export const REAL_STRUCTURAL_RELATIONSHIPS: StructuralRelationship[] = [
  r("client", "decoraciones-pilar", "approval", "b22c15b6-25a6-4982-908c-1d4496966bd2", "awaits_approval"),
  r("client", "decoraciones-pilar", "approval", "seed-approval-pilar-design", "awaits_approval"),
  r("client", "decoraciones-pilar", "approval", "seed-approval-pilar-launch", "awaits_approval"),
  r("client", "decoraciones-pilar", "invoice", "56eb0b57-5130-4757-b01b-7b76bdcc2083", "billed"),
  r("client", "decoraciones-pilar", "invoice", "seed-inv-2026-03", "billed"),
  r("client", "decoraciones-pilar", "invoice", "seed-inv-2026-04", "billed"),
  r("client", "decoraciones-pilar", "invoice", "seed-inv-2026-05", "billed"),
  r("client", "decoraciones-pilar", "invoice", "seed-inv-pilar-01", "billed"),
  r("client", "decoraciones-pilar", "invoice", "seed-inv-pilar-02", "billed"),
  r("client", "tapia-tile-marble", "invoice", "0c3c1b03-8668-4f17-8df3-a78c609cd672", "billed"),
  r("client", "tapia-tile-marble", "invoice", "seed-inv-tapia-01", "billed"),
  r("project", "bay-area-custom-shirts-inc", "phase", "bay-area-custom-shirts-inc:design", "has_phase"),
  r("project", "bay-area-custom-shirts-inc", "phase", "bay-area-custom-shirts-inc:dev", "has_phase"),
  r("project", "bay-area-custom-shirts-inc", "phase", "bay-area-custom-shirts-inc:launch", "has_phase"),
  r("project", "bay-area-custom-shirts-inc", "phase", "bay-area-custom-shirts-inc:onboarding", "has_phase"),
  r("project", "bay-area-custom-shirts-inc", "phase", "bay-area-custom-shirts-inc:strategy", "has_phase"),
  r("project", "decoraciones-pilar", "phase", "decoraciones-pilar:design", "has_phase"),
  r("project", "decoraciones-pilar", "phase", "decoraciones-pilar:dev", "has_phase"),
  r("project", "decoraciones-pilar", "phase", "decoraciones-pilar:launch", "has_phase"),
  r("project", "decoraciones-pilar", "phase", "decoraciones-pilar:onboarding", "has_phase"),
  r("project", "decoraciones-pilar", "phase", "decoraciones-pilar:strategy", "has_phase"),
  r("project", "elite-vac-service", "phase", "elite-vac-service:design", "has_phase"),
  r("project", "elite-vac-service", "phase", "elite-vac-service:dev", "has_phase"),
  r("project", "elite-vac-service", "phase", "elite-vac-service:launch", "has_phase"),
  r("project", "elite-vac-service", "phase", "elite-vac-service:onboarding", "has_phase"),
  r("project", "elite-vac-service", "phase", "elite-vac-service:strategy", "has_phase"),
  r("project", "tapia-tile-marble", "phase", "tapia-tile-marble:design", "has_phase"),
  r("project", "tapia-tile-marble", "phase", "tapia-tile-marble:dev", "has_phase"),
  r("project", "tapia-tile-marble", "phase", "tapia-tile-marble:launch", "has_phase"),
  r("project", "tapia-tile-marble", "phase", "tapia-tile-marble:onboarding", "has_phase"),
  r("project", "tapia-tile-marble", "phase", "tapia-tile-marble:strategy", "has_phase"),
  r("client", "bay-area-custom-shirts-inc", "project", "bay-area-custom-shirts-inc", "has_project"),
  r("client", "decoraciones-pilar", "project", "decoraciones-pilar", "has_project"),
  r("client", "elite-vac-service", "project", "elite-vac-service", "has_project"),
  r("client", "tapia-tile-marble", "project", "tapia-tile-marble", "has_project"),
  r("phase", "bay-area-custom-shirts-inc:design", "task", "bay-area-custom-shirts-inc:design:0", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:design", "task", "bay-area-custom-shirts-inc:design:1", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:design", "task", "bay-area-custom-shirts-inc:design:2", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:design", "task", "bay-area-custom-shirts-inc:design:3", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:dev", "task", "bay-area-custom-shirts-inc:dev:0", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:dev", "task", "bay-area-custom-shirts-inc:dev:1", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:dev", "task", "bay-area-custom-shirts-inc:dev:2", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:dev", "task", "bay-area-custom-shirts-inc:dev:3", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:launch", "task", "bay-area-custom-shirts-inc:launch:0", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:launch", "task", "bay-area-custom-shirts-inc:launch:1", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:launch", "task", "bay-area-custom-shirts-inc:launch:2", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:launch", "task", "bay-area-custom-shirts-inc:launch:3", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:onboarding", "task", "bay-area-custom-shirts-inc:onboarding:0", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:onboarding", "task", "bay-area-custom-shirts-inc:onboarding:1", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:onboarding", "task", "bay-area-custom-shirts-inc:onboarding:2", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:strategy", "task", "bay-area-custom-shirts-inc:strategy:0", "has_task"),
  r("phase", "bay-area-custom-shirts-inc:strategy", "task", "bay-area-custom-shirts-inc:strategy:1", "has_task"),
  r("phase", "elite-vac-service:design", "task", "elite-vac-service:design:0", "has_task"),
  r("phase", "elite-vac-service:design", "task", "elite-vac-service:design:1", "has_task"),
  r("phase", "elite-vac-service:design", "task", "elite-vac-service:design:2", "has_task"),
  r("phase", "elite-vac-service:design", "task", "elite-vac-service:design:3", "has_task"),
  r("phase", "elite-vac-service:dev", "task", "elite-vac-service:dev:0", "has_task"),
  r("phase", "elite-vac-service:dev", "task", "elite-vac-service:dev:1", "has_task"),
  r("phase", "elite-vac-service:dev", "task", "elite-vac-service:dev:2", "has_task"),
  r("phase", "elite-vac-service:dev", "task", "elite-vac-service:dev:3", "has_task"),
  r("phase", "elite-vac-service:onboarding", "task", "elite-vac-service:onboarding:0", "has_task"),
  r("phase", "elite-vac-service:onboarding", "task", "elite-vac-service:onboarding:1", "has_task"),
  r("phase", "elite-vac-service:onboarding", "task", "elite-vac-service:onboarding:2", "has_task"),
  r("phase", "elite-vac-service:strategy", "task", "elite-vac-service:strategy:0", "has_task"),
  r("phase", "elite-vac-service:strategy", "task", "elite-vac-service:strategy:1", "has_task"),
  r("phase", "tapia-tile-marble:design", "task", "tapia-tile-marble:design:3", "has_task"),
  r("phase", "tapia-tile-marble:design", "task", "tapia-tile-marble:design:4", "has_task"),
  r("phase", "tapia-tile-marble:design", "task", "tapia-tile-marble:design:5", "has_task"),
  r("phase", "tapia-tile-marble:dev", "task", "tapia-tile-marble:dev:0", "has_task"),
  r("phase", "tapia-tile-marble:dev", "task", "tapia-tile-marble:dev:1", "has_task"),
  r("phase", "tapia-tile-marble:dev", "task", "tapia-tile-marble:dev:2", "has_task"),
  r("phase", "tapia-tile-marble:dev", "task", "tapia-tile-marble:dev:3", "has_task"),
  r("phase", "tapia-tile-marble:dev", "task", "tapia-tile-marble:dev:4", "has_task"),
  r("phase", "tapia-tile-marble:dev", "task", "tapia-tile-marble:dev:5", "has_task"),
  r("phase", "tapia-tile-marble:launch", "task", "tapia-tile-marble:launch:0", "has_task"),
  r("phase", "tapia-tile-marble:launch", "task", "tapia-tile-marble:launch:1", "has_task"),
  r("phase", "tapia-tile-marble:launch", "task", "tapia-tile-marble:launch:2", "has_task"),
  r("phase", "tapia-tile-marble:launch", "task", "tapia-tile-marble:launch:3", "has_task"),
  r("client", "decoraciones-pilar", "audit", "30f8b44f-8b23-4cde-a558-61d503c986fe", "measured_by"),
  r("client", "decoraciones-pilar", "audit", "404ffa2e-fca2-46ce-9909-bc4aaf172a1d", "measured_by"),
  r("client", "decoraciones-pilar", "audit", "75ba41a1-1e86-450a-8026-8885547e9959", "measured_by"),
  r("client", "decoraciones-pilar", "audit", "seed-aud-pilar-2026-01-mob", "measured_by"),
  r("client", "decoraciones-pilar", "audit", "seed-aud-pilar-2026-02-mob", "measured_by"),
  r("client", "decoraciones-pilar", "audit", "seed-aud-pilar-2026-03-mob", "measured_by"),
  r("client", "decoraciones-pilar", "audit", "seed-aud-pilar-2026-04-mob", "measured_by"),
  r("client", "decoraciones-pilar", "audit", "seed-aud-pilar-2026-05-mob", "measured_by"),
  r("client", "decoraciones-pilar", "audit", "seed-aud-pilar-2026-06-dsk", "measured_by"),
  r("client", "decoraciones-pilar", "audit", "seed-aud-pilar-2026-06-mob", "measured_by"),
  r("client", "tapia-tile-marble", "audit", "7b90d464-9065-480a-9c93-ab5caf30aa14", "measured_by"),
  r("client", "tapia-tile-marble", "audit", "8c25af02-ec03-410b-98c6-72298b8b15f1", "measured_by"),
  r("client", "decoraciones-pilar", "document", "f0911bd7-19aa-4dc5-97c2-16398c3c9218", "owns_document"),
  r("client", "decoraciones-pilar", "document", "seed-doc-pilar-contract-v1", "owns_document"),
  r("client", "decoraciones-pilar", "document", "seed-doc-pilar-prop-v1", "owns_document"),
  r("client", "decoraciones-pilar", "document", "seed-doc-pilar-prop-v2", "owns_document"),
  r("client", "tapia-tile-marble", "document", "babed1df-2536-4e30-a80c-59227ae67c1d", "owns_document"),
  r("prospect", "bay-area-custom-shirts-inc", "client", "bay-area-custom-shirts-inc", "promoted_to"),
  r("document", "f0911bd7-19aa-4dc5-97c2-16398c3c9218", "document", "seed-doc-pilar-contract-v1", "supersedes"),
  r("document", "seed-doc-pilar-prop-v2", "document", "seed-doc-pilar-prop-v1", "supersedes"),];
