// lib/renderMarkdown.ts — the single safe markdown → HTML renderer (hardening pass).
//
// SCOPE: presentation sanitisation only. No read-model, no derivation, no vault access, no frozen
// contract. It replaces three separate `marked.parse(body)` calls that fed `dangerouslySetInnerHTML`
// with no sanitiser (marked has not sanitised since v5; the option was removed).
//
// WHY THIS MATTERED: there is a complete attacker-controlled path into rendered markdown. The
// prospect URL-intake route extracts a remote site's <meta name="description"> with a regex that
// performs no entity escaping, writes it into the prospect's markdown body, and /sales/[prospect]
// renders that body through marked into dangerouslySetInnerHTML. A hostile prospect site could
// therefore execute script in the operator's console.
//
// APPROACH — two layers, no new dependency:
//   1. Escape `<` and `>` in the SOURCE before parsing. No HTML element can form, so raw-HTML
//      injection is structurally impossible. Markdown syntax does not use angle brackets, so
//      headings, lists, emphasis, tables, code and links all still render. (Verified against the
//      live vault: no markdown there depends on raw HTML.) The cost is autolinks (`<https://x>`),
//      which are not used.
//   2. Neutralise dangerous URL schemes in the OUTPUT. Escaping angle brackets does not stop
//      `[click](javascript:alert(1))` — marked emits that as a real href. Because step 1 guarantees
//      every tag in the output was generated by marked itself, post-processing its well-formed
//      output is predictable and sufficient.

import { marked } from "marked";

marked.setOptions({ gfm: true, breaks: false });

/** Escape the two characters that can begin or end an HTML tag. */
function escapeAngleBrackets(source: string): string {
  return source.replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/**
 * Schemes that must never appear in a generated href/src. `data:` is included because
 * `data:text/html,...` is script-capable in some navigation contexts.
 */
const DANGEROUS_SCHEME = /^\s*(?:javascript|vbscript|data|file|about)\s*:/i;

/** Replace href/src values carrying a dangerous scheme with an inert value. */
function neutraliseUrlAttributes(html: string): string {
  return html.replace(/\s(href|src)\s*=\s*"([^"]*)"/gi, (match, attr: string, value: string) => {
    // Decode the entity forms an attacker could use to hide the scheme from a naive check.
    const decoded = value
      .replace(/&#x([0-9a-f]+);?/gi, (_, hex: string) => String.fromCharCode(parseInt(hex, 16)))
      .replace(/&#(\d+);?/g, (_, dec: string) => String.fromCharCode(parseInt(dec, 10)))
      .replace(/&colon;/gi, ":")
      .replace(/[\x00-\x1F\x7F]/g, ""); // control chars used to split "java\0script:"

    if (DANGEROUS_SCHEME.test(decoded)) {
      return ` ${attr}="#"`;
    }
    return match;
  });
}

/**
 * Render vault markdown to HTML that is safe to pass to dangerouslySetInnerHTML.
 * Synchronous: `marked.parse` returns a string when no async extension is registered, and none is.
 */
export function renderMarkdown(source: string): string {
  if (!source) return "";
  const html = marked.parse(escapeAngleBrackets(source)) as string;
  return neutraliseUrlAttributes(html);
}